language: node_js

node_js:
  - "16"

cache:
  directories:
    - node_modules

install:
  - npm install

before_script:
  - npm run lint
  - npm run format

script:
  - npm run build:prod

deploy:


