version: 2.1

orbs:
  node: circleci/node@16.17.0

jobs:
  test:
    executor: node/default
    steps:
      - run:
          name: unit test
          command: npm run test:unit
      - run:
          name: e2e test
          command: npm run test:e2e 
  build:
    executor: node/default
    steps:
      - checkout
      - run:
          name: production build
          command: npm run build:prod
  deploy:
    executor: node/default
    steps:
      - run:
          name: deploy
          command: echo "start deploy ..."
workflows:
  example:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
