version: 2.1
jobs:
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: unit test
          command: sh "npm run test:unit"
      - run:
          name: e2e test
          command: sh "npm run test:e2e" 
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: production build
          command: sh "npm run build:prod"
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: echo "start deploy ..."
workflows:
  example:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
