version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Run unit test
          command: echo "start unit test ..."
      - run:
          name: Run e2e test
          command: echo "start e2e test ..."
  build:
    executor: node/default
    branches:
      only:
        - main
    steps:
      - checkout
      - run:
          name: Run production build
          command: echo "start build ..."
              
  deploy:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Run deploy
          command: echo "start deploy ..."
workflows:
  example:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
